[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://i.ibb.co https://imgbb.com https://freeimage.host https://i.pravatar.cc data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; connect-src 'self' https://chatify-api.up.railway.app; font-src 'self' https://cdnjs.cloudflare.com;"